# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "nvme"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "tmpfs";
    fsType = "tmpfs";
    options = [ "defaults" "mode=755" "size=2G" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/4b631190-2a02-4ccc-a2eb-e50a0fa542f4";
    fsType = "btrfs";
    options = [ "subvol=home" ];
    neededForBoot = true;
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/4b631190-2a02-4ccc-a2eb-e50a0fa542f4";
    fsType = "btrfs";
    options = [ "subvol=nix" ];
  };

  # Real, persistent storage. Everything that needs to survive a reboot
  # (SSH host keys, machine-id, NetworkManager connections, etc.) lives
  # here and gets bind-mounted into the ephemeral root at boot.
  fileSystems."/persist" = {
    device = "/dev/disk/by-uuid/4b631190-2a02-4ccc-a2eb-e50a0fa542f4";
    fsType = "btrfs";
    options = [ "subvol=persist" ];
    neededForBoot = true; # impermanence needs this mounted before it can bind-mount from it
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/55E1-06F6";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/4bdbcadf-639a-493a-a64d-29486c6d6115"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.npu.enable = true;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
